export const ADD_ITEM = 'STORY/ADD_ITEM';
export const RECEIVE_DATA = 'STORY/RECEIVE_DATA';
export const APPEND_DATA = 'STORY/APPEND_DATA';
export const JOINING = 'STORY/JOINING';
export const UPDATE_STORY = 'STORY/UPDATE_STORY';
