export const ADD_ITEM = 'STORY/ADD_ITEM';
export const RECEIVE_DATA = 'STORY/RECEIVE_DATA';
export const APPEND_DATA = 'STORY/APPEND_DATA';
export const JOINING = 'STORY/JOINING';
export const FETCH_SUCCESS = 'STORY/FETCH_SUCCESS';
export const FETCH_START = 'STORY/FETCH_START';
