export const ADD_ITEM = 'STORIES/ADD_ITEM';
export const RECEIVE_DATA = 'STORIES/RECEIVE_DATA';
export const APPEND_DATA = 'STORIES/APPEND_DATA';
export const JOINING = 'STORIES/JOINING';
export const FETCH_SUCCESS = 'STORIES/FETCH_SUCCESS';
export const FETCH_START = 'STORIES/FETCH_START';
export const FETCH_ERROR = 'STORIES/FETCH_ERROR';
